#!/bin/bash

help () {
cat >&2 <<EOF
$cmd_name -- Borg backup archive pruning wrapper

Syntax:  $cmd_name [options] REPO ARCHIVE

Wrapper options:
-n --keep=NUM	Maximum number of archives to keep and rotate
-t --time=NUM[ymwdhM][...]
		Valid time window for keeping archives,
		for ex. 6m (6 months), 4w (4 weeks), 7d12h (7 days + 12 hours)
-E --exp=NUM	Exponent: pruning algorithm uses a power based pattern, high
		values lead to a fast growing distance between latter and
		former dates. 1 gives an even distribution, realistic values
		are between 1 and 5, default is 3
-h --help	Print this help screen

Usable Borg options:
-p --progress	show progress information
--list		output verbose list of archives
-s --stats	print statistics for the deleted archive
EOF
exit
}

cmd_name=${0##*/}
(( $# )) || help
log_msg () { echo $(date +%Y-%m-%d\ %H%M.%S)"  ($cmd_name)  $@" >&2; }
export TMPDIR=/dev/shm LC_ALL=C
shopt -s nullglob
IFS=$'\n'
declare -i exp=3
args_par=ntE
. sk-args-canon

while [[ $1 = -* ]]; do
   case "${1:1}" in
      n|keep=) keep=$2; shift ;;
      t|time=) time=$(sk-time-to-sec "$2"); shift ;;
      E|exp=) exp=$2; shift ;;
      h|help) help ;;
      p|progress) b_opt+=(-p) ;;
      list) b_opt+=(--list) ;;
      s|stats) b_opt+=(-s) ;;
      *) log_msg "Error: unknown option '$1'"; exit 1 ;;
   esac
   shift
done
(( $# != 2 )) && {
   log_msg 'Error: must specify repository and archive prefix'
   exit 1
}

repo=$1
arch=$2
rm_list=($(borg list --short -a "$arch-[0-9][0-9][0-9][0-9]*" "$repo" | \
   keep=$keep time=$time exp=$exp sk-prune-dates))

(( ${#rm_list[@]} )) && borg delete ${b_opt[@]} "$repo" "${rm_list[@]}"
