#!/bin/bash

(( $# < 2 )) || [[ $1 == -h ]] && {
cat >&2 <<EOF
FRPO - File Recovery Priority Organizer
purge metadata list from fully synched files

Usage:  ${0##*/} SYNC_DIR METADATA_LIST [...]
EOF
exit
}

export LC_ALL=C TMPDIR=/dev/shm
disk_l=$(mktemp)
tmp1=$(mktemp)
tmp2=$(mktemp)
tmp3=$(mktemp)
trap 'rm -f -- $disk_l "$tmp"{1..3}' EXIT

(cd "$1" && find -type f -printf "%P\t%s\n") | sort -o $disk_l
[[ -s $disk_l ]] || {
    echo 'Error: sync folder empty or incorrect parameters'
    exit
}

for list in "${@:2}"; do
    # Enforcing use of .ls as source lists extension to ease wildcard selection of source lists
    # and avoid accidental insertion of done lists (.done) as input
    [[ $list != *.ls ]] && {
        echo "List '$list' skipped, please '.ls' file extension for lists."
        continue
    }
    done=${list::-2}done
    # Get file name and size, paste in inverted field position, add a leading index number (+p) with
    # \a (bell) char further used as separator to group file name and size, sort by file name
    # (index is adopted to sit remaining metadata lines at their original order at the end)
    paste <(cut -f3 -- "$list") <(cut -f2 -- "$list") | nl -w1 -sp$'\a' | sort -t$'\a' -k2 -o $tmp1
    # Getting index list of metadata to purge (if any), as referencing fully synched files
    join --nocheck-order -t$'\a' -12 -o 1.1 -- $tmp1 $disk_l | sort -o $tmp2
    [[ -s $tmp2 ]] && {
        echo -n "List '$list': "
        cut -d$'\a' -f1 $tmp1 | sort -o $tmp3
        # Getting index list of incomplete/missing files by comparing full list with purge list
        comm --check-order -13 $tmp{2,3} > $tmp1
        if [[ -s $tmp1 ]]; then
            sed -nf $tmp2 -- "$list" >> "$done"
            sed -nf $tmp1 -- "$list" > $tmp3
            mv -- $tmp3 "$list"
            msg=
        else
            if [[ -s $done ]]; then
                cat -- "$list" >> "$done"
                rm -- "$list"
            else
                mv -- "$list" "$done"
            fi
            msg=' (completed)'
        fi
        i=$(wc -l $tmp2)
        echo "${i%%[^0-9]*} references purged$msg"
    }
done
